# fly.toml app configuration file generated for streamlit-summer-sunset-6833 on 2024-02-06T14:11:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'streamlit-summer-sunset-6833'
primary_region = 'ams'

[build]
  builder = 'paketobuildpacks/builder:base'
# comment the builder line if you have a dockerfile
[env]
  PORT = '8501'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
